### ISSUE TITLE
Profile image goes right when URL is short

### ISSUE THREAD

**Issue by wldhg** [AngryPowman/hexo-theme-prontera#3]
In index page, when profile url is short, profile image goes right.
In other words, `float: right` does not work.
So I resolved this problem like below.
```CSS
/*
    On source/scss/_partial/sidebar.scss
    (Modify the file like below)
*/
....
#about-panel {
    display: flex;
    position: relative;
    border-bottom: 1px solid #eeeeee;
    padding-bottom: 10px;
    .info {
        .title {
            font-size: 18px;
        }
        .url {
            color: #666666;
            font-size: 16px;
            font-weight: 200;
        }
        .bio {
            padding-top: 14px;
            font-size: 15px;
            font-weight: 200;
            color: #777777;
        }
    }
    .avatar {
        float: right;
	position: absolute;
	right: 0;
        margin-left: 50px;
        border-radius: 100%;
        border: 3px solid #F2F5F7;
        width: 86px;
        height: 86px;
    }
}
....
```
